/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocksSol from "./Mocks.sol";
export type { mocksSol };
export type { YieldVault } from "./YieldVault";
