/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockLendingProtocol__factory } from "./MockLendingProtocol__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
