/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockLendingProtocol } from "./MockLendingProtocol";
export type { MockUSDC } from "./MockUSDC";
